site_name: asli-pipeline
nav:
  - Getting Started: index.md
  - Configuration: config.md
  - Running and Automating Pipeline: running_pipeline.md
  - Deployment Example: deployment.md
  - About: about.md
theme:
  name: readthedocs
  logo: https://cdn.web.bas.ac.uk/bas-style-kit/0.7.3/img/logos-symbols/bas-logo-inverse-transparent-64.png
markdown_extensions:
  - admonition